config/routes.rb
Aaw::Application.routes.draw do

  resources :posts
  match '/auth/:provider/callback' => 'authentications#create'
  resources :authentications

  get "authentications/index"
  get "authentications/create"
  get "authentications/destroy"

  resources :searches
  get "pages/home"
  get "pages/about"
  match "/words/search" => "words#search"

  resources :words do
    member do
      get 'search'
    end
  end
  resources :adoptions
  resources :pages

  match '/home', :to => 'pages#home'
  match '/about',:to => 'pages#about'
  match '/user' => "users#show", :as => :user_root
  match '/usershow', :to => 'users#show'

  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users, :only => [:index, :show]

   root :to => 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  require 'twitter'
  require 'fb_graph'

  ## the user has many authentications
  ## the user can have many adoptions
  ## the user has many words through adoptions
  ## the user has many posts

  has_many :authentications
  has_many :adoptions
  has_many :words, :through => :adoptions
  has_many :posts

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

   ## method to allow user have omniauth hash passed to it
   ## authentication is created from the omniauth hash
   ## the fields of the authentication are mapped from the hash_from_omniauth method
   def apply_omniauth(omniauth)
     case omniauth['provider']
       when 'facebook'
         self.apply_facebook(omniauth)
       when 'twitter'
         self.apply_twitter(omniauth)
     end
    authentications.build(hash_from_omniauth(omniauth))
   end

  ## find_tweets method
  ## Save the users tweets to the database
  def find_tweets(current_user)
    @screen_name = current_user.authentications[2].to_s
    @another_tweet = self.twitter.user_timeline(@screen_name)
    @tweet = Tweets.new
    @another_tweet.each do |t|
      @tweet.screenname = t.screen_name
      @tweet.text = t.text
      @tweet.created_at = t.created_at
    end
     @tweet.save
  end

  ## contact Facebook to acccess the FbGraph
  def facebook
    @fb_user ||= FbGraph::User.me(self.authentications.find_by_provider('facebook').token)
    @fb_user.fetch
  end

  def facebook_search
    @fb_user ||= FbGraph::User.me(self.authentications.find_by_provider('facebook').token)
  end

  def facebook_searchable
    @fb_user ||=FbGraph::Searchable.search(params)
  end

   ## overriding the password validations
  def password_required?
    ## only validate a password when no authentication password is available
    ## delegate to super so we can inherit that behaviour too
   (authentications.empty? || !password.blank?) && super
  end

  ## contact Twitter to instantiate a new Twitter Client
  ## pass the provider token and the provider secret
  def twitter
    unless @twitter_user
      provider = self.authentications.find_by_provider('twitter')
      @twitter_user = Twitter::Client.new(:oauth_token => provider.token, :oauth_token_secret => provider.secret )rescue nil
    end
    @twitter_user
  end

    def twitter_search
    unless @twitter_user
      provider = self.authentications.find_by_provider('twitter')
      @twitter_user = Twitter::Search.new
    end
    @twitter_user
    end

  def tweet_search

  end

  protected

  ## method to build an authentication from facebook
  def apply_facebook(omniauth)
  if (extra = omniauth['extra']['user_hash'] rescue false)
    self.email = (extra['email'] rescue '')
  end
end

  ## method to build an authentication from twitter
  def apply_twitter(omniauth)
    if (extra = omniauth['extra']['user_hash'] rescue false)
    end
  end

  ## method to map the details from the omniauth hash to the attributes of the authentication
    def hash_from_omniauth(omniauth)
      {
          :provider => omniauth['provider'],
          :uid => omniauth['uid'],
          :token => (omniauth['credentials']['token'] rescue nil),
          :secret => (omniauth['credentials']['secret'] rescue nil),
          :screenname => (omniauth['user_info']['nickname'] rescue nil)
      }
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  ## show all Users
  def index
    @user = User.all
  end
  ## Display the Users Profile
  #
  # =================================
  #
  #
  def show
    if(params[:id] != nil)
      @user = User.find(params[:id])
    else
      @user = current_user
    end
    ## @user = params[:id].nil? ? User.find(params[:id]) : current_user
    ## @user = current_user
    ## find the users authentications
    ## if the users authentication provider is twitter then search their twitter status timeline
    ## else find the users facebook timeline with words containing the users adopted words.
    @user.find_tweets(current_user)
   screenname = @user.authentications
   screenname.each do |n|
     if n.provider == "twitter"
    @another_tweet = @user.twitter.user_timeline(n.screenname).paginate(:per_page => 5, :page => params[:another_tweet])
      else
        @adoptions = @user.adoptions
        @adoptions.each do |w|
        @word =  Word.find_by_id(w[:word_id]).word
        end
        @facebook_post = @user.facebook.fetch.home(:q => 'alabandical')
        @facebook_post.collection.each do |m|
          @message = m[:message]
          @message2 = m[:comments][:data]
        end
      end
    end
  end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>User#index</h1>
<table>
    <tr>
    <th>User Id</th>
    <th>Email</th>
  </tr>
<% @user.each do |user|%>
   <tr>
      <td><%= user.id %></td>
      <td><%= user.email %></td>
     <td>This user has adopted <%= user.words.count %> words </td>
     <td> <%= link_to "MY PROFILE", user_path(user) %> </td>
     <td> <%= link_to 'user x', usershow_path%></td>
     <!--<% user.words.each do |w| %>-->
     <!--<td> <%= w[:word]%></td>-->
     <!--<% end %>-->
   </tr>
<% end %>
</table>

app/views/users/show.html.erb
<div><p>Welcome Back <%= current_user.email %></p></div>
<div class="user_container">

  <div class="word_box">
    <% if @user.adoptions.length != 0 %>
        <p>

        <h2>You have adopted <%= @user.adoptions.length %> words</h2>

        <% @user.adoptions.each do |w| %>
            <table class="word_table">
              <tr>
                <td class='gab'><%= Word.find_by_id(w[:word_id]).word.capitalize %></td>
              </tr>
              <tr>
                <td><%= Word.find_by_id(w[:word_id]).meaning %></td>
              </tr>
            </table>
        <% end %>
        <button class="button">Make a Comment</button>
        <div id="post_form" style="display: none">
          <%= form_for Post.new(:user => @user, :poster => current_user.id) do |f| %>
              <%= f.hidden_field :user_id %>
              <p>
                <%= f.label :title %> </br>
                <%= f.text_field :title %>
              </p>

              <p style="display:none">
                <%= f.label :poster %> </br>
                <%= f.text_field :poster%>
              </p>

              <p>
                <%= f.label :content, "Comment" %> <br/>
                <%= f.text_area :content, :rows => 8 %>
              </p>
              <p><%= f.submit ("Add Review") %> </p>

          <% end %>
        </div>
    <% end %>


  </div>
  <div class="tweets">
    <% if @another_tweet.nil? %>
        <% @facebook_post.each do |m| %>
            <table class="word_table">
              <tr><td><%= image_tag('facebook.png', :size => "64x64", :alt => "Twitter Logo") %></td><td class="gab"></td><td class="gab"><%= m.message %></td></tr>
              <tr><td><%= image_tag('facebook.png', :size => "64x64", :alt => "Twitter Logo") %></td><td class="gab"></td><td class="gab"> <%= @message %> </td></tr>
              <% @message2.each do |m| %>
              <tr><td><%= image_tag('facebook.png', :size => "64x64", :alt => "Twitter Logo") %></td><td class="gab"></td><td class="gab"> <%= m[:message] %></td></tr>
                <% end %>
            </table>
         <% end %>
         <p class="adopt_button"><%= link_to "Adopt Another Word", words_path %></p>
    <% else %>

        <h1> Your most recent Tweets with your adopted words </h1></br>
         <%= will_paginate @another_tweet, :param_name => :another_tweet %>
        <% @another_tweet.each do |w| %>
            <table class="word_table">
              <tr>
                <td><%= image_tag('twitter-logo.jpg', :size => "64x64", :alt => "Twitter Logo") %></td>
                <td class="gab"><%= w.text %></td>
              </tr>
              <tr>
                <td><%= w.screen_name %></td>
                <td> <%= w.created_at %></td>
              </tr>
            </table>
        <% end %>
        </br>
        <p class="adopt_button"><%= link_to "Adopt Another Word", words_path %></p>
<% end %>

  </div>
</div>