config/routes.rb
Aaw::Application.routes.draw do

  resources :posts
  match '/auth/:provider/callback' => 'authentications#create'
  resources :authentications

  get "authentications/index"
  get "authentications/create"
  get "authentications/destroy"

  resources :searches
  get "pages/home"
  get "pages/about"
  match "/words/search" => "words#search"

  resources :words do
    member do
      get 'search'
    end
  end
  resources :adoptions
  resources :pages

  match '/home', :to => 'pages#home'
  match '/about',:to => 'pages#about'
  match '/user' => "users#show", :as => :user_root
  match '/usershow', :to => 'users#show'

  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users, :only => [:index, :show]

   root :to => 'pages#home'

end

app/models/word.rb
class Word < ActiveRecord::Base
  ## Words belong to an adoption
  ## Users may have many adoptions
  ## Words may have many posts through adoptions

  belongs_to :adoption
  has_many :searches
  has_many :users, :through => :adoptions
  has_many :posts, :through => :adoptions


  ## search method with 3 paramaters passed to it
  ## the find method uses a get method and an sql query

def self.search(search, search2, search3)
  if search
    #where('word LIKE ?', "%#{search}%")
    find(:all, :conditions => ['word LIKE ? AND category LIKE ? AND word_type LIKE ?' ,"%#{search}%", "%#{search2[:category]}%", "%#{search3[:type]}%"])
    #else
  else
    scoped
  end
end

#  def self.search(search,search1, search2, search3)
#    if search
#      find(:all, :conditions => ['word LIKE ? OR category LIKE ?","%#{search}"])
#
#    end)
#    end
#  end


end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  ## index action finds words by searching either the word, category or the type of word.
  ## using the paginate method only 15 words are displayed per page
   def index
  @words = Word.search(params[:search], params[:search2], params[:search3]).paginate(:per_page => 15,:page => params[:page])
  end

   ## show action will search for a word with a particular parameter
   ## if the current user is has a twitter authentication it will find tweets with that particular word
   ## if the current user has a facebook authentication it will find public facebook updates with that particular word
  def show
    @word = Word.find(params[:id])
    if current_user.authentications[2]=="twitter"
    @tweet_search =  current_user.twitter.search(@word.word)
    else
      @tweet_search
      end
  end

  ## method to adopt a word
  def adopt_word
    @word = Word.find(params[:id])
    @adoption = Adoption.new
    @adoption.adopt_a_word(word)
  end

   ## method to search word
   ## method is passed 3 parameters
  def search
    @search = Search.new(params[:search], params[:search2],params[:search3])

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render json: @search, status: :created, location: @search }
      else
        format.html { render action: "new" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
 <% form_for :dump, :url=>{:controller=>"words", :action=>"new"}, :html => { :multipart => true } do |f| -%>
 <table>
   <tr>
     <td>
      <label for="dump_file">
        Select a CSV File :
      </label>
     </td>
     <td >
       <%= f.file_field :file -%>
     </td>
   </tr>
   <tr>
     <td colspan='2'>
       <%= submit_tag 'Submit' -%>
     </td>
   </tr>
 </table>
<% end -%>

app/views/words/_words.html.erb
<table>
  <tr>
    <th>WORD</th>
    <th>TYPE</th>
    <th>MEANING</th>
  </tr>
  <% @words.each do |wordy| %>
      <tr class="<%= cycle('oddrow', 'evenrow') %>">
        <td><b><%= wordy.word.capitalize %></b></td>
        <td><%= wordy.word_type %></td>
        <td><%= wordy.meaning %></td>
        <td><%= link_to 'Adopt Word', adoptions_path(:id => wordy), :method => :post %></td>
        <td>
          <% if user_signed_in? %>
              <%= link_to 'View This Word', wordy %>
          <% else %>
              <%= link_to "Show", new_user_session_path %>.
          <% end %></td>
      </tr>
  <% end %>

</table>
</br>
<%= will_paginate @words, previous_label: h("<"), next_label: h(">") %>

app/views/words/index.html.erb
<!--<%= render :partial => "/searches/form"%>-->
<div id="words_container">
<div id="checkbox">

  <%= form_tag(@search, :url => searches_path) do |f| %>
  <% end %>

  <%= form_tag words_path, :method => 'get' do %>
<table class="search">

  <tr><td onmouseover="this.toggleClass()">Search Word</td><td><%= text_field_tag :search, params[:search] %></td></tr>
  <tr></tr>
  <tr><td>Type</td><td><%= select(:search3, :type, [['All',''],['Adjective', 'adj'], ['Noun', 'noun'],['Verb', 'verb']],{ "style" => "width:200px" }) %></td></tr>
  <tr></tr>
  <tr><td>Category</td><td><%= select(:search2, :category, [['All',''],['Kind', 'kind'], ['Mean', 'mean'],['Medical', 'medical'],['General','general'],['Science','science'],['Funny','funny']]) %></td></tr>
  <tr></tr>
</table>
  <%= submit_tag "Search", :word => nil, :width => 300 %> </br></br>
  <%= link_to "Search All Words", words_path %>
<% end %>

</div>
<div id="words">
<%= render 'words' %>
</div>
<br />
</div>

app/views/words/index.js.erb
$("#words").html("<%= escape_javascript(render("words")) %>");

app/views/words/new.html.erb
<h1>New wordy</h1>

<%= render 'form' %>

<%= link_to 'Back', word_path%>

app/views/words/show.html.erb
<div class="user_container">
  <div class='word_box'>
    <table class="word_show">
      <tr>
        <td class='gab'><%= @word.word.capitalize %></td>
        <td id="word_type">(<%= @word.word_type %>)</td>
        </tr>
      </table>
    </br></br>
        <p id="word_meaning">--<%= @word.meaning.capitalize %>--</p>

        <p id="word_usage">"<%= @word.usage %>"</p>

         </br></br>
        <p class="adopt_button"><%= link_to 'Adopt This Word', adoptions_path(:id => @word), :method => :post %></p>


  </div>

  <p class="gab2"><% if  @tweet_search.nil? || @tweet_search.empty? %>
        There are no records of <%= @word.word %> on Twitter.
        Why don't you adopt
        <%= link_to adoptions_path(:id => @word),:method => :post do %>
            <%= @word.word %>
            <%end %>
            and your tweet about your adopted word will be displayed here.

</p>
        <% else %>
             <% @tweet_search.each do |t|  %>
            <table class="word_table">
              <tr>
                <td><%= image_tag('twitter-logo.jpg', :size => "64x64", :alt => "Twitter Logo") %></td>
                <td class="gab"><%= t[:text] %></td>
              </tr>
              <tr>
                <td><%= t.user[:screen_name] %></td>
                <td > <%= t.user[:name] %></td>
              </tr>
            </table>
           <% end %>
      <% end %>

</div>