config/routes.rb
Aaw::Application.routes.draw do

  resources :posts
  match '/auth/:provider/callback' => 'authentications#create'
  resources :authentications

  get "authentications/index"
  get "authentications/create"
  get "authentications/destroy"

  resources :searches
  get "pages/home"
  get "pages/about"
  match "/words/search" => "words#search"

  resources :words do
    member do
      get 'search'
    end
  end
  resources :adoptions
  resources :pages

  match '/home', :to => 'pages#home'
  match '/about',:to => 'pages#about'
  match '/user' => "users#show", :as => :user_root
  match '/usershow', :to => 'users#show'

  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users, :only => [:index, :show]

   root :to => 'pages#home'

end

app/models/search.rb
class Search < ActiveRecord::Base

  belongs_to :word

  def words(parameters)
    @words = find_words(parameters)
  end

  def find_words(parameters)
    #Word.find(:all, :conditions => conditions)
    Word.find(:all, :conditions => ["word like ?",parameters])

  end

  def keyword_conditions
    ["words.word LIKE ?", "%#{keywords}%"]unless keywords.blank?
  end

#  def category_conditions
#    ["words.category = ?", category] unless category.blank?
#  end

  def category_conditions
    ["words.category LIKE ?", "%#{category}"]
  end
  def conditions
    [conditions_clauses.join(' AND '), *conditions_options]
  end

  def conditions_clauses
    conditions_parts.map{ |condition| condition.first}
  end
  def conditions_options
    conditions_parts.map{|condition| condition[1..-1]}.flatten
  end
  def conditions_parts
    methods.grep(/_conditions$/).map { |m| send(m)}.compact
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @searches }
    end
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
    @search = Search.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searches/new
  # GET /searches/new.json
  def new
    @search = Search.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searches/1/edit
  def edit
    @search = Search.find(params[:id])
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(params[:search])

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render json: @search, status: :created, location: @search }
      else
        format.html { render action: "new" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /searches/1
  # PUT /searches/1.json
  def update
    @search = Search.find(params[:id])

    respond_to do |format|
      if @search.update_attributes(params[:search])
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search = Search.find(params[:id])
    @search.destroy

    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :ok }
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_tag('/words/search', :method => :get) %>

  <div class="field">
    <%= label_tag :keywords %><br />
    <%= text_field_tag :keywords %>
  </div>

    <%= select(:search, :category, [['Funny', 'funny'], ['Mean', 'mean']]) %>

  <div class="actions">
    <%= submit_tag %>
  </div>

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<h1>Listing searches</h1>

<table>
  <tr>
    <th>Keywords</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @searches.each do |search| %>
  <tr>
    <td><%= search.keywords %></td>
    <td><%= search.category %></td>
    <td><%= link_to 'Show', search %></td>
    <td><%= link_to 'Edit', edit_search_path(search) %></td>
    <td><%= link_to 'Destroy', search, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<div><p><%= @search.words[0].word%></p> </div>
<div><p><%= @search.words[0].word_type%></p> </div>
<div><p><%= @search.words[0].time%></p> </div>
<div><p><%= @search.words[0].meaning%></p> </div>
<div><p><%= @search.words[0].usage%></p> </div>
<div><p><%= @search.words[0].category%></p> </div>