config/routes.rb
Aaw::Application.routes.draw do

  resources :posts
  match '/auth/:provider/callback' => 'authentications#create'
  resources :authentications

  get "authentications/index"
  get "authentications/create"
  get "authentications/destroy"

  resources :searches
  get "pages/home"
  get "pages/about"
  match "/words/search" => "words#search"

  resources :words do
    member do
      get 'search'
    end
  end
  resources :adoptions
  resources :pages

  match '/home', :to => 'pages#home'
  match '/about',:to => 'pages#about'
  match '/user' => "users#show", :as => :user_root
  match '/usershow', :to => 'users#show'

  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users, :only => [:index, :show]

   root :to => 'pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Adopt a Word | <%= @home %> </title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js", "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js", "application" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>
<body id='body'>
  <div id="user_nav">
    <%= link_to "HOME", home_path %>
    <%= link_to "ADOPT A WORD", words_path %>
    <%= link_to "ABOUT", about_path %>
    <% if user_signed_in? %>
        <%= link_to "MY PROFILE", usershow_path %>
        Signed in as <%= current_user.email %>. Not you?
        <%= link_to "SIGN OUT", destroy_user_session_path, :method => :delete, :confirm => 'Are you sure?' %>
    <% else %>
        <div id="auth2">
          <%= render :partial => 'authentications/index', :locals => {:authentications => @authentications} %>
        </div>
    <% end %>
  </div>

<p class="notice"><%= notice %></p>

<p class="alert"><%= alert %></p>

<div class="site_body">
  <%= yield %>
</div>

</body>
</html>